version: '3'
services:
  cdk:
    build: .
    tty: true
    working_dir: /workdir
    volumes:
      - ness-cdk:/workdir
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_DEFAULT_OUTPUT: ${AWS_DEFAULT_OUTPUT}
      FCM_CREDENTIALS_JSON_BASE64: ${FCM_CREDENTIALS_JSON_BASE64}
volumes:
  ness-cdk:
    external: true
